services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile

    ports:
      - "80:80"

    networks:
      redApi:
        ipv4_address: 172.20.10.2

    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # PHP
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app_dev

    networks:
      redApi:
        ipv4_address: 172.20.10.3

    volumes:
      # - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: Jur@doIntra
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: b4hr3UQEO6d5
      MYSQL_DATABASE:
        mifj

        #      REDIS_HOST: cache
        # REDIS_PORT: 6379
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly define on linux
      - host.docker.internal:host-gateway

  # mysql
  db:
    image: mysql:8.0

    ports:
      - "3306:3306"

    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      redApi:
        ipv4_address: 172.20.10.4

    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Jur@doIntra
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: b4hr3UQEO6d5
      MYSQL_DATABASE: mifj

  # redis
  # cache:
  #   image: redis:latest
  #   ports:
  #     - "6379"

networks:
  redApi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1

volumes:
  mysqldata:
