services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile

    ports:
      - "80:80"

    networks:
      redApi:
        ipv4_address: 172.20.10.2

    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # PHP
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: app

    networks:
      redApi:
        ipv4_address: 172.20.10.3
  # mysql
  db:
    image: mysql:8.0

    volumes:
      - mysqldata:/var/lib/mysql

    networks:
      redApi:
        ipv4_address: 172.20.10.4

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: mifj

  # redis
networks:
  redApi:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1

volumes:
  mysqldata:
